<?php
/**
 * Created by PhpStorm.
 * User: Making
 * Date: 2017/2/28
 * Time: 15:27
 */

namespace App\Admin\Extensions;


use Encore\Admin\Form\Field;

class EditorDatetable extends Field
{
	public function __construct($column, array $arguments)
	{
		$this->column = $column;
		parent::__construct($column, $arguments);
	}

	public function render()
	{
		$column=$this->column;
		$column['getKey']=$this->form->model()->getKey();
		$collection=collect($column);
		$keys['keys']=$collection->keys()->all();
		foreach ($keys['keys'] as $key_value){
			$column['keys'][$key_value]=$key_value;
		}
//		dd('admin.form.'.$column['view']);
		return view('admin.form.'.$column['view'], compact('column'));// TODO: Change the autogenerated stub
	}

}