<?php
/**
 * Created by PhpStorm.
 * User: Making
 * Date: 2017/2/22
 * Time: 9:17
 */

namespace App\Admin\Extensions;


use App\Admin\Models\Goods\Good;
use App\Admin\Models\Images\Image;
use App\Admin\Models\Images\Image_attach;
use Encore\Admin\Form\Field;

class Fileinput extends Field
{
//    public function  __construct($column, array $arguments)
//    {
//        parent::__construct($column, $arguments);
//    }

	protected $view = 'admin.form.fileinput';
	protected static $css = [
		'/fileinput/css/fileinput.min.css',
		'/fileinput/themes/explorer/theme.css'
	];
	protected static $js = [
		'/fileinput/js/plugins/canvas-to-blob.min.js',
		'/fileinput/js/plugins/sortable.min.js',
		'/fileinput/js/plugins/purify.min.js',
		'/fileinput/js/fileinput.min.js',
		'/fileinput/js/locales/zh.js',
		'/fileinput/themes/explorer/theme.js',
	];

	public function render()
	{
		$url = url('/admin/fileupload');
		$removeUrl = url('/admin/fileupload/remove');
		$csrf_token = csrf_token();
		$good_model = $this->form->model();
		if ($good_model['goods_id']) {
			if ($good_model) {
				$image_attachs = Good::find($good_model['goods_id'])->image_attach()->get()->toArray();
				foreach ($image_attachs as $image_attach) {
					$initialPreviewConfig[] = [
						'caption' => 'transport',
						'size' => '',
						'url' => $removeUrl,
						'key' => $image_attach['image_id']
					];
					$images = Image::where('image_id', $image_attach['image_id'])->get()->toArray();
					foreach ($images as $image)
						$image_url[] = $image['url'];
				}
			}
		}
			$json_string = @json_encode($image_url);
			if ($json_string == 'null') {
				$json_string = '[]';
			}
			$initialPreview = @json_encode($initialPreviewConfig);
			if ($initialPreview == 'null') {
				$initialPreview = '[]';
			}

			$this->script = <<<EOT
 $.ajaxSetup({
        'headers': {
            'X-CSRF-TOKEN': '$csrf_token'
        }
    });
    $('#file-fr').fileinput({
//        uploadAsync: false, //默认异步上传
//        showUpload: true,
//        maxFilesNum : 2,//上传最大的文件数量 
        actionUpload:true,
        showCaption: false,
        language: 'zh',
        uploadUrl: '$url',
        previewFileIcon: "<i class='glyphicon glyphicon-king'></i>",
        allowedFileExtensions: ['jpg', 'png', 'gif','jpeg'],
        dropZoneEnabled: true,//是否显示拖拽区域
        overwriteInitial: false,
        initialPreviewAsData: true,
        initialPreview: $json_string,
        initialPreviewConfig: $initialPreview,
    });
     $('#file-fr').on('fileuploaded', function(event, data, previewId, index) {
             var form = data.form, files = data.files, extra = data.extra,
              response = data.response, reader = data.reader;
              console.log(response);//打印出返回的json
              console.log(response.paths);//打印出路径
                });
EOT;

		return parent::render(); // TODO: Change the autogenerated stub
	}
}