<?php
/**
 * Created by PhpStorm.
 * User: Making
 * Date: 2017/3/10
 * Time: 16:49
 */

namespace App\Admin\Extensions;


use Encore\Admin\Form\Field;

class Message extends Field
{
	protected static $js = [
		"https://unpkg.com/element-ui/lib/index.js"
	];
	protected static $css = [
		"https://unpkg.com/element-ui/lib/theme-default/index.css"
	];

	public function render()
	{
		
		return parent::render(); // TODO: Change the autogenerated stub
	}
}