<?php

/**
 * Created by PhpStorm.
 * User: Making
 * Date: 2017/6/3
 * Time: 21:40
 */
use App\Order;

class OrderTest extends PHPUnit_Framework_TestCase
{
	
	protected $order;

	protected $productOne;

	protected $productTow;

	public function setUp()
	{
		$this->order = new Order;
		$this->productOne = new \App\Product('iWatch', 3000);
		$this->productTow = new \App\Product('iPhone', 10000);

		$this->order->add($this->productOne);
		$this->order->add($this->productTow);
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	/** @test */
	public function a_order_consists_products()
	{

		$this->assertCount(2, $this->order->products());
	}

	/** @test */
	public function we_can_get_total_cost_from_all_products_of_an_order()
	{
		$this->assertEquals(13000, $this->order->total());
	}
}
