<?php
/**
 * Created by PhpStorm.
 * User: Making
 * Date: 2017/6/3
 * Time: 20:34
 */
use App\Product;


class ProductTest extends PHPUnit_Framework_TestCase
{
	protected $product;

	public function setUp()
	{
		$this->product = new Product('iPhone 7', 10000);
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	/** @test */
	public function a_product_hash_a_name()
	{

		$this->assertEquals('iPhone 7', $this->product->name());
	}

	/** @test */
	public function a_product_hash_a_price()
	{

		$this->assertEquals(10000, $this->product->price());
	}

	/** @test */
	public function a_product_can_be_sold_with_discount()
	{

		$this->product->setDiscount(9);

		$this->assertEquals(9000, $this->product->price());
	}
}